-- Create roadmap_weeks table
CREATE TABLE IF NOT EXISTS roadmap_weeks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  certification_id BIGINT REFERENCES certifications(id) ON DELETE CASCADE,
  week_number INTEGER NOT NULL,
  title TEXT,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(certification_id, week_number)
);

-- Create roadmap_week_machines junction table
CREATE TABLE IF NOT EXISTS roadmap_week_machines (
  week_id BIGINT REFERENCES roadmap_weeks(id) ON DELETE CASCADE,
  machine_id INTEGER REFERENCES htb_machines(id) ON DELETE CASCADE,
  PRIMARY KEY (week_id, machine_id)
);

-- Create roadmap_week_techniques junction table
CREATE TABLE IF NOT EXISTS roadmap_week_techniques (
  week_id BIGINT REFERENCES roadmap_weeks(id) ON DELETE CASCADE,
  technique_id INTEGER REFERENCES techniques(id) ON DELETE CASCADE,
  PRIMARY KEY (week_id, technique_id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_roadmap_weeks_certification_id ON roadmap_weeks(certification_id);
CREATE INDEX IF NOT EXISTS idx_roadmap_week_machines_week_id ON roadmap_week_machines(week_id);
CREATE INDEX IF NOT EXISTS idx_roadmap_week_techniques_week_id ON roadmap_week_techniques(week_id);

-- Enable RLS
ALTER TABLE roadmap_weeks ENABLE ROW LEVEL SECURITY;
ALTER TABLE roadmap_week_machines ENABLE ROW LEVEL SECURITY;
ALTER TABLE roadmap_week_techniques ENABLE ROW LEVEL SECURITY;

-- Public read access
CREATE POLICY "Roadmap weeks are viewable by everyone" ON roadmap_weeks FOR SELECT USING (true);
CREATE POLICY "Roadmap week machines are viewable by everyone" ON roadmap_week_machines FOR SELECT USING (true);
CREATE POLICY "Roadmap week techniques are viewable by everyone" ON roadmap_week_techniques FOR SELECT USING (true);
